PRE PROCESSORS DIRECTIVES ARE THE STATEMENTS WHICH INCLUDE # IN FRONT
EG. #INCLUDE<STDIO.H>
# DEFINE MAX 10
ETC.
THE FIRSTLY CHANGE THE VALUE WHEREVER THE VARIABLE IS USED IN THE PROGRAM AND THE PROGRAM IS COMPILED .




to find upper matrix if(i<j) is ued
